spring.application.name=whoever-seeks-finds

# Server Configuration
server.port=8080
server.servlet.context-path=/

# JSF Configuration
joinfaces.jsf.project-stage=Development
joinfaces.jsf.facelets-skip-comments=true
joinfaces.jsf.primefaces.theme=saga

# Logging
logging.level.org.springframework=INFO
logging.level.com.unp.finds=DEBUG
